version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    ports:
      - "8180:8180"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - /Users/jarotball/study/SpringBootLearningPath/explorecli/keycloak/data:/opt/keycloak/data
      - /Users/jarotball/study/SpringBootLearningPath/explorecli/keycloak/conf:/opt/keycloak/conf
    command: start-dev --http-port 8180 --http-relative-path /

